import { Response } from "express"

/**
 * Creates a standardized response, with the response code in params and a custom message forwarded via json
 * @param res 
 * @param status 
 * @param message 
 */
export function failRequest(res:Response, status: number, message: string): void {
    res.status(status).json({ message: message }) as any
}

/**
 * Returns true if the email is valid, false otherwise
 * @param email 
 * @returns {boolean}
 */
export function isEmailValid(email: string): boolean {
    // Generated by ChatGPT
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    return emailRegex.test(email)
}